"""added columns to run

Revision ID: 3cce3b9cf2a0
Revises: b1f2d3eccabf
Create Date: 2018-03-28 22:51:01.302841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cce3b9cf2a0'
down_revision = 'b1f2d3eccabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('columns', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'columns')
    # ### end Alembic commands ###
