"""add inferred_columns

Revision ID: 7f9f5faedb3d
Revises: c7587cb51e9d
Create Date: 2018-05-07 16:55:55.552637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9f5faedb3d'
down_revision = 'c7587cb51e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('result_inffered_columns', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'result_inffered_columns')
    # ### end Alembic commands ###
