"""added extract code

Revision ID: 8377b06cfce6
Revises: 3cce3b9cf2a0
Create Date: 2018-04-03 15:14:54.563501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8377b06cfce6'
down_revision = '3cce3b9cf2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('column_extract_code', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'column_extract_code')
    # ### end Alembic commands ###
