"""added columns

Revision ID: b1f2d3eccabf
Revises: 58cfc4e94e0b
Create Date: 2018-03-28 22:11:10.219878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f2d3eccabf'
down_revision = '58cfc4e94e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('columns', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'columns')
    # ### end Alembic commands ###
