"""increase column size

Revision ID: c7587cb51e9d
Revises: 29cafeeb30a1
Create Date: 2018-05-07 11:32:21.746283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7587cb51e9d'
down_revision = '29cafeeb30a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'experiment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'file_content', 'run', ['run_id'], ['id'])
    op.alter_column('run', 'run_result',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=500),
               type_=sa.String(length=25000),
               existing_nullable=True)
    op.create_foreign_key(None, 'run', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'run', 'experiment', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.alter_column('run', 'run_result',
               existing_type=sa.String(length=25000),
               type_=mysql.VARCHAR(collation='utf8_bin', length=500),
               existing_nullable=True)
    op.drop_constraint(None, 'file_content', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    # ### end Alembic commands ###
