"""empty message

Revision ID: d8e6c72a8bc4
Revises: 831f4f5783db
Create Date: 2018-07-07 13:54:30.013613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e6c72a8bc4'
down_revision = '831f4f5783db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'columns',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=4000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'columns',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
